# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85fd24aa4d951294d340189706b77c22"
name = "muster-tracker"
handle = "muster-tracker"
application_url = "https://regulations-baking-seem-what.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://regulations-baking-seem-what.trycloudflare.com/auth/callback",
  "https://regulations-baking-seem-what.trycloudflare.com/auth/shopify/callback",
  "https://regulations-baking-seem-what.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
